# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from oxford_dictionaries_python_sdk.paths.inflections_source_lang_word_id_filters.get import CheckAndRetrieveRootForm
from oxford_dictionaries_python_sdk.apis.tags.lemmatron_api_raw import LemmatronApiRaw


class LemmatronApi(
    CheckAndRetrieveRootForm,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LemmatronApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LemmatronApiRaw(api_client)
