# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from oxford_dictionaries_python_sdk.paths.stats_frequency_ngrams_source_lang_corpus_ngram_size.get import GetNgramFrequenciesRaw
from oxford_dictionaries_python_sdk.paths.stats_frequency_words_source_lang.get import GetWordFrequenciesRaw
from oxford_dictionaries_python_sdk.paths.stats_frequency_word_source_lang.get import GetWordFrequencyRaw


class LexiStatsApiRaw(
    GetNgramFrequenciesRaw,
    GetWordFrequenciesRaw,
    GetWordFrequencyRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
