# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from oxford_dictionaries_python_sdk.paths.search_source_lang.get import GetMatchesRaw
from oxford_dictionaries_python_sdk.paths.search_source_search_language_translationstarget_search_language.get import PossibleTranslationsRaw


class SearchApiRaw(
    GetMatchesRaw,
    PossibleTranslationsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
