# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from oxford_dictionaries_python_sdk.paths.entries_source_lang_word_id_antonyms.get import GetAntonyms
from oxford_dictionaries_python_sdk.paths.entries_source_lang_word_id_synonyms.get import GetSimilarWords
from oxford_dictionaries_python_sdk.paths.entries_source_lang_word_id_synonymsantonyms.get import GetSynonymsAntonyms
from oxford_dictionaries_python_sdk.apis.tags.thesaurus_api_raw import ThesaurusApiRaw


class ThesaurusApi(
    GetAntonyms,
    GetSimilarWords,
    GetSynonymsAntonyms,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ThesaurusApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ThesaurusApiRaw(api_client)
