# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from oxford_dictionaries_python_sdk.paths.grammatical_features_source_language.get import GetGrammaticalFeatures
from oxford_dictionaries_python_sdk.paths.lexicalcategories_language.get import GetLexicalCategories
from oxford_dictionaries_python_sdk.paths.domains_source_domains_language_target_domains_language.get import ListAvailableDomains
from oxford_dictionaries_python_sdk.paths.filters.get import ListAvailableFilters
from oxford_dictionaries_python_sdk.paths.languages.get import ListAvailableLanguages
from oxford_dictionaries_python_sdk.paths.registers_source_register_language_target_register_language.get import ListBilingualRegisters
from oxford_dictionaries_python_sdk.paths.filters_endpoint.get import ListEndpointFilters
from oxford_dictionaries_python_sdk.paths.domains_source_language.get import ListMonolingualDomains
from oxford_dictionaries_python_sdk.paths.regions_source_language.get import ListMonolingualRegions
from oxford_dictionaries_python_sdk.paths.registers_source_language.get import ListMonolingualRegisters
from oxford_dictionaries_python_sdk.apis.tags.utility_api_raw import UtilityApiRaw


class UtilityApi(
    GetGrammaticalFeatures,
    GetLexicalCategories,
    ListAvailableDomains,
    ListAvailableFilters,
    ListAvailableLanguages,
    ListBilingualRegisters,
    ListEndpointFilters,
    ListMonolingualDomains,
    ListMonolingualRegions,
    ListMonolingualRegisters,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UtilityApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UtilityApiRaw(api_client)
