# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from oxford_dictionaries_python_sdk.paths.grammatical_features_source_language.get import GetGrammaticalFeaturesRaw
from oxford_dictionaries_python_sdk.paths.lexicalcategories_language.get import GetLexicalCategoriesRaw
from oxford_dictionaries_python_sdk.paths.domains_source_domains_language_target_domains_language.get import ListAvailableDomainsRaw
from oxford_dictionaries_python_sdk.paths.filters.get import ListAvailableFiltersRaw
from oxford_dictionaries_python_sdk.paths.languages.get import ListAvailableLanguagesRaw
from oxford_dictionaries_python_sdk.paths.registers_source_register_language_target_register_language.get import ListBilingualRegistersRaw
from oxford_dictionaries_python_sdk.paths.filters_endpoint.get import ListEndpointFiltersRaw
from oxford_dictionaries_python_sdk.paths.domains_source_language.get import ListMonolingualDomainsRaw
from oxford_dictionaries_python_sdk.paths.regions_source_language.get import ListMonolingualRegionsRaw
from oxford_dictionaries_python_sdk.paths.registers_source_language.get import ListMonolingualRegistersRaw


class UtilityApiRaw(
    GetGrammaticalFeaturesRaw,
    GetLexicalCategoriesRaw,
    ListAvailableDomainsRaw,
    ListAvailableFiltersRaw,
    ListAvailableLanguagesRaw,
    ListBilingualRegistersRaw,
    ListEndpointFiltersRaw,
    ListMonolingualDomainsRaw,
    ListMonolingualRegionsRaw,
    ListMonolingualRegistersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
