# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oxford_dictionaries_python_sdk.type.arrayofstrings import Arrayofstrings
from oxford_dictionaries_python_sdk.type.categorized_text_list import CategorizedTextList
from oxford_dictionaries_python_sdk.type.cross_references_list import CrossReferencesList
from oxford_dictionaries_python_sdk.type.examples_list import ExamplesList
from oxford_dictionaries_python_sdk.type.pronunciations_list import PronunciationsList
from oxford_dictionaries_python_sdk.type.thesaurus_link import ThesaurusLink
from oxford_dictionaries_python_sdk.type.translations_list import TranslationsList
from oxford_dictionaries_python_sdk.type.variant_forms_list import VariantFormsList

class RequiredSense(TypedDict):
    pass

class OptionalSense(TypedDict, total=False):
    crossReferenceMarkers: Arrayofstrings

    crossReferences: CrossReferencesList

    definitions: Arrayofstrings

    domains: Arrayofstrings

    examples: ExamplesList

    # The id of the sense that is required for the delete procedure
    id: str

    notes: CategorizedTextList

    pronunciations: PronunciationsList

    regions: Arrayofstrings

    registers: Arrayofstrings

    short_definitions: Arrayofstrings

    # Ordered list of subsenses of a sense
    subsenses: 'typing.List["Sense"]'

    # Ordered list of links to the Thesaurus Dictionary
    thesaurusLinks: typing.List[ThesaurusLink]

    translations: TranslationsList

    variantForms: VariantFormsList

class Sense(RequiredSense, OptionalSense):
    pass
