# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oxford_dictionaries_python_sdk.type.sentences_lexical_entry import SentencesLexicalEntry

class RequiredSentencesEntry(TypedDict):
    # The identifier of a word
    id: str

    # IANA language code
    language: str

    # A grouping of various senses in a specific language, and a lexical category that relates to a word
    lexicalEntries: typing.List[SentencesLexicalEntry]

    # A given written or spoken realisation of a an entry, lowercased.
    word: str

class OptionalSentencesEntry(TypedDict, total=False):
    # The json object type. Could be 'headword', 'inflection' or 'phrase'
    type: str

class SentencesEntry(RequiredSentencesEntry, OptionalSentencesEntry):
    pass
