# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oxford_dictionaries_python_sdk.type.thesaurus_sense import ThesaurusSense
from oxford_dictionaries_python_sdk.type.variant_forms_list import VariantFormsList

class RequiredThesaurusEntry(TypedDict):
    pass

class OptionalThesaurusEntry(TypedDict, total=False):
    # Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
    homographNumber: str

    # Complete list of senses
    senses: typing.List[ThesaurusSense]

    variantForms: VariantFormsList

class ThesaurusEntry(RequiredThesaurusEntry, OptionalThesaurusEntry):
    pass
