# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from oxford_dictionaries_python_sdk.type.wordlist_results import WordlistResults

class RequiredWordlist(TypedDict):
    pass

class OptionalWordlist(TypedDict, total=False):
    # Additional Information provided by OUP
    metadata: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    results: WordlistResults

class Wordlist(RequiredWordlist, OptionalWordlist):
    pass
