# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oxford_dictionaries_python_sdk import schemas  # noqa: F401


class ArrayOfRelatedEntries(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    A list of written or spoken words
    """


    class MetaOapg:
        min_items = 1
        
        @staticmethod
        def items() -> typing.Type['ArrayOfRelatedEntriesItem']:
            return ArrayOfRelatedEntriesItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['ArrayOfRelatedEntriesItem'], typing.List['ArrayOfRelatedEntriesItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ArrayOfRelatedEntries':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'ArrayOfRelatedEntriesItem':
        return super().__getitem__(i)

from oxford_dictionaries_python_sdk.model.array_of_related_entries_item import ArrayOfRelatedEntriesItem
