# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oxford_dictionaries_python_sdk import schemas  # noqa: F401


class LemmatronLexicalEntry(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Description of an entry for a particular part of speech and grammatical features
    """


    class MetaOapg:
        required = {
            "inflectionOf",
            "lexicalCategory",
            "language",
            "text",
        }
        
        class properties:
        
            @staticmethod
            def inflectionOf() -> typing.Type['InflectionsList']:
                return InflectionsList
            language = schemas.StrSchema
            lexicalCategory = schemas.StrSchema
            text = schemas.StrSchema
        
            @staticmethod
            def grammaticalFeatures() -> typing.Type['GrammaticalFeaturesList']:
                return GrammaticalFeaturesList
            __annotations__ = {
                "inflectionOf": inflectionOf,
                "language": language,
                "lexicalCategory": lexicalCategory,
                "text": text,
                "grammaticalFeatures": grammaticalFeatures,
            }
    
    inflectionOf: 'InflectionsList'
    lexicalCategory: MetaOapg.properties.lexicalCategory
    language: MetaOapg.properties.language
    text: MetaOapg.properties.text
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inflectionOf"]) -> 'InflectionsList': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["language"]) -> MetaOapg.properties.language: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lexicalCategory"]) -> MetaOapg.properties.lexicalCategory: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["grammaticalFeatures"]) -> 'GrammaticalFeaturesList': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["inflectionOf", "language", "lexicalCategory", "text", "grammaticalFeatures", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inflectionOf"]) -> 'InflectionsList': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["language"]) -> MetaOapg.properties.language: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lexicalCategory"]) -> MetaOapg.properties.lexicalCategory: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["grammaticalFeatures"]) -> typing.Union['GrammaticalFeaturesList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["inflectionOf", "language", "lexicalCategory", "text", "grammaticalFeatures", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        inflectionOf: 'InflectionsList',
        lexicalCategory: typing.Union[MetaOapg.properties.lexicalCategory, str, ],
        language: typing.Union[MetaOapg.properties.language, str, ],
        text: typing.Union[MetaOapg.properties.text, str, ],
        grammaticalFeatures: typing.Union['GrammaticalFeaturesList', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LemmatronLexicalEntry':
        return super().__new__(
            cls,
            *args,
            inflectionOf=inflectionOf,
            lexicalCategory=lexicalCategory,
            language=language,
            text=text,
            grammaticalFeatures=grammaticalFeatures,
            _configuration=_configuration,
            **kwargs,
        )

from oxford_dictionaries_python_sdk.model.grammatical_features_list import GrammaticalFeaturesList
from oxford_dictionaries_python_sdk.model.inflections_list import InflectionsList
