# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oxford_dictionaries_python_sdk import schemas  # noqa: F401


class LexicalEntry(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Description of an entry for a particular part of speech
    """


    class MetaOapg:
        required = {
            "lexicalCategory",
            "language",
            "text",
        }
        
        class properties:
            language = schemas.StrSchema
            lexicalCategory = schemas.StrSchema
            text = schemas.StrSchema
        
            @staticmethod
            def derivativeOf() -> typing.Type['ArrayOfRelatedEntries']:
                return ArrayOfRelatedEntries
        
            @staticmethod
            def derivatives() -> typing.Type['ArrayOfRelatedEntries']:
                return ArrayOfRelatedEntries
            
            
            class entries(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Entry']:
                        return Entry
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Entry'], typing.List['Entry']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'entries':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Entry':
                    return super().__getitem__(i)
        
            @staticmethod
            def grammaticalFeatures() -> typing.Type['GrammaticalFeaturesList']:
                return GrammaticalFeaturesList
        
            @staticmethod
            def notes() -> typing.Type['CategorizedTextList']:
                return CategorizedTextList
        
            @staticmethod
            def pronunciations() -> typing.Type['PronunciationsList']:
                return PronunciationsList
        
            @staticmethod
            def variantForms() -> typing.Type['VariantFormsList']:
                return VariantFormsList
            __annotations__ = {
                "language": language,
                "lexicalCategory": lexicalCategory,
                "text": text,
                "derivativeOf": derivativeOf,
                "derivatives": derivatives,
                "entries": entries,
                "grammaticalFeatures": grammaticalFeatures,
                "notes": notes,
                "pronunciations": pronunciations,
                "variantForms": variantForms,
            }
    
    lexicalCategory: MetaOapg.properties.lexicalCategory
    language: MetaOapg.properties.language
    text: MetaOapg.properties.text
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["language"]) -> MetaOapg.properties.language: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lexicalCategory"]) -> MetaOapg.properties.lexicalCategory: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["derivativeOf"]) -> 'ArrayOfRelatedEntries': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["derivatives"]) -> 'ArrayOfRelatedEntries': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["entries"]) -> MetaOapg.properties.entries: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["grammaticalFeatures"]) -> 'GrammaticalFeaturesList': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notes"]) -> 'CategorizedTextList': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pronunciations"]) -> 'PronunciationsList': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["variantForms"]) -> 'VariantFormsList': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["language", "lexicalCategory", "text", "derivativeOf", "derivatives", "entries", "grammaticalFeatures", "notes", "pronunciations", "variantForms", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["language"]) -> MetaOapg.properties.language: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lexicalCategory"]) -> MetaOapg.properties.lexicalCategory: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["derivativeOf"]) -> typing.Union['ArrayOfRelatedEntries', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["derivatives"]) -> typing.Union['ArrayOfRelatedEntries', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["entries"]) -> typing.Union[MetaOapg.properties.entries, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["grammaticalFeatures"]) -> typing.Union['GrammaticalFeaturesList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notes"]) -> typing.Union['CategorizedTextList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pronunciations"]) -> typing.Union['PronunciationsList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["variantForms"]) -> typing.Union['VariantFormsList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["language", "lexicalCategory", "text", "derivativeOf", "derivatives", "entries", "grammaticalFeatures", "notes", "pronunciations", "variantForms", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        lexicalCategory: typing.Union[MetaOapg.properties.lexicalCategory, str, ],
        language: typing.Union[MetaOapg.properties.language, str, ],
        text: typing.Union[MetaOapg.properties.text, str, ],
        derivativeOf: typing.Union['ArrayOfRelatedEntries', schemas.Unset] = schemas.unset,
        derivatives: typing.Union['ArrayOfRelatedEntries', schemas.Unset] = schemas.unset,
        entries: typing.Union[MetaOapg.properties.entries, list, tuple, schemas.Unset] = schemas.unset,
        grammaticalFeatures: typing.Union['GrammaticalFeaturesList', schemas.Unset] = schemas.unset,
        notes: typing.Union['CategorizedTextList', schemas.Unset] = schemas.unset,
        pronunciations: typing.Union['PronunciationsList', schemas.Unset] = schemas.unset,
        variantForms: typing.Union['VariantFormsList', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LexicalEntry':
        return super().__new__(
            cls,
            *args,
            lexicalCategory=lexicalCategory,
            language=language,
            text=text,
            derivativeOf=derivativeOf,
            derivatives=derivatives,
            entries=entries,
            grammaticalFeatures=grammaticalFeatures,
            notes=notes,
            pronunciations=pronunciations,
            variantForms=variantForms,
            _configuration=_configuration,
            **kwargs,
        )

from oxford_dictionaries_python_sdk.model.array_of_related_entries import ArrayOfRelatedEntries
from oxford_dictionaries_python_sdk.model.categorized_text_list import CategorizedTextList
from oxford_dictionaries_python_sdk.model.entry import Entry
from oxford_dictionaries_python_sdk.model.grammatical_features_list import GrammaticalFeaturesList
from oxford_dictionaries_python_sdk.model.pronunciations_list import PronunciationsList
from oxford_dictionaries_python_sdk.model.variant_forms_list import VariantFormsList
