# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oxford_dictionaries_python_sdk import schemas  # noqa: F401


class ThesaurusSense(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def antonyms() -> typing.Type['SynonymsAntonyms']:
                return SynonymsAntonyms
        
            @staticmethod
            def domains() -> typing.Type['Arrayofstrings']:
                return Arrayofstrings
        
            @staticmethod
            def examples() -> typing.Type['ExamplesList']:
                return ExamplesList
            id = schemas.StrSchema
        
            @staticmethod
            def regions() -> typing.Type['Arrayofstrings']:
                return Arrayofstrings
        
            @staticmethod
            def registers() -> typing.Type['Arrayofstrings']:
                return Arrayofstrings
            
            
            class subsenses(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ThesaurusSense']:
                        return ThesaurusSense
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ThesaurusSense'], typing.List['ThesaurusSense']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'subsenses':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ThesaurusSense':
                    return super().__getitem__(i)
        
            @staticmethod
            def synonyms() -> typing.Type['SynonymsAntonyms']:
                return SynonymsAntonyms
            __annotations__ = {
                "antonyms": antonyms,
                "domains": domains,
                "examples": examples,
                "id": id,
                "regions": regions,
                "registers": registers,
                "subsenses": subsenses,
                "synonyms": synonyms,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["antonyms"]) -> 'SynonymsAntonyms': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domains"]) -> 'Arrayofstrings': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["examples"]) -> 'ExamplesList': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["regions"]) -> 'Arrayofstrings': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["registers"]) -> 'Arrayofstrings': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subsenses"]) -> MetaOapg.properties.subsenses: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["synonyms"]) -> 'SynonymsAntonyms': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["antonyms", "domains", "examples", "id", "regions", "registers", "subsenses", "synonyms", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["antonyms"]) -> typing.Union['SynonymsAntonyms', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domains"]) -> typing.Union['Arrayofstrings', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["examples"]) -> typing.Union['ExamplesList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["regions"]) -> typing.Union['Arrayofstrings', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["registers"]) -> typing.Union['Arrayofstrings', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subsenses"]) -> typing.Union[MetaOapg.properties.subsenses, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["synonyms"]) -> typing.Union['SynonymsAntonyms', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["antonyms", "domains", "examples", "id", "regions", "registers", "subsenses", "synonyms", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        antonyms: typing.Union['SynonymsAntonyms', schemas.Unset] = schemas.unset,
        domains: typing.Union['Arrayofstrings', schemas.Unset] = schemas.unset,
        examples: typing.Union['ExamplesList', schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        regions: typing.Union['Arrayofstrings', schemas.Unset] = schemas.unset,
        registers: typing.Union['Arrayofstrings', schemas.Unset] = schemas.unset,
        subsenses: typing.Union[MetaOapg.properties.subsenses, list, tuple, schemas.Unset] = schemas.unset,
        synonyms: typing.Union['SynonymsAntonyms', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ThesaurusSense':
        return super().__new__(
            cls,
            *args,
            antonyms=antonyms,
            domains=domains,
            examples=examples,
            id=id,
            regions=regions,
            registers=registers,
            subsenses=subsenses,
            synonyms=synonyms,
            _configuration=_configuration,
            **kwargs,
        )

from oxford_dictionaries_python_sdk.model.arrayofstrings import Arrayofstrings
from oxford_dictionaries_python_sdk.model.examples_list import ExamplesList
from oxford_dictionaries_python_sdk.model.synonyms_antonyms import SynonymsAntonyms
