# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oxford_dictionaries_python_sdk import schemas  # noqa: F401


class ThesaurusEntry(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            homographNumber = schemas.StrSchema
            
            
            class senses(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ThesaurusSense']:
                        return ThesaurusSense
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ThesaurusSense'], typing.List['ThesaurusSense']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'senses':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ThesaurusSense':
                    return super().__getitem__(i)
        
            @staticmethod
            def variantForms() -> typing.Type['VariantFormsList']:
                return VariantFormsList
            __annotations__ = {
                "homographNumber": homographNumber,
                "senses": senses,
                "variantForms": variantForms,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["homographNumber"]) -> MetaOapg.properties.homographNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["senses"]) -> MetaOapg.properties.senses: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["variantForms"]) -> 'VariantFormsList': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["homographNumber", "senses", "variantForms", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["homographNumber"]) -> typing.Union[MetaOapg.properties.homographNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["senses"]) -> typing.Union[MetaOapg.properties.senses, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["variantForms"]) -> typing.Union['VariantFormsList', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["homographNumber", "senses", "variantForms", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        homographNumber: typing.Union[MetaOapg.properties.homographNumber, str, schemas.Unset] = schemas.unset,
        senses: typing.Union[MetaOapg.properties.senses, list, tuple, schemas.Unset] = schemas.unset,
        variantForms: typing.Union['VariantFormsList', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ThesaurusEntry':
        return super().__new__(
            cls,
            *args,
            homographNumber=homographNumber,
            senses=senses,
            variantForms=variantForms,
            _configuration=_configuration,
            **kwargs,
        )

from oxford_dictionaries_python_sdk.model.thesaurus_sense import ThesaurusSense
from oxford_dictionaries_python_sdk.model.variant_forms_list import VariantFormsList
