# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

import unittest

import oxford_dictionaries_python_sdk
from oxford_dictionaries_python_sdk.model.retrieve_entry import RetrieveEntry
from oxford_dictionaries_python_sdk import configuration


class TestRetrieveEntry(unittest.TestCase):
    """RetrieveEntry unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
