# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from oxford_dictionaries_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from oxford_dictionaries_python_sdk.api_response import AsyncGeneratorResponse
from oxford_dictionaries_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from oxford_dictionaries_python_sdk import schemas  # noqa: F401

from oxford_dictionaries_python_sdk.model.wordlist import Wordlist as WordlistSchema

from oxford_dictionaries_python_sdk.type.wordlist import Wordlist

from ...api_client import Dictionary
from oxford_dictionaries_python_sdk.pydantic.wordlist import Wordlist as WordlistPydantic

from . import path

# Query params
QSchema = schemas.StrSchema


class PrefixSchema(
    schemas.EnumBase,
    schemas.BoolSchema
):


    class MetaOapg:
        enum_value_to_name = {
            False: "FALSE",
            True: "TRUE",
        }
    
    @schemas.classproperty
    def FALSE(cls):
        return cls(False)
    
    @schemas.classproperty
    def TRUE(cls):
        return cls(True)
RegionsSchema = schemas.StrSchema
LimitSchema = schemas.StrSchema
OffsetSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'q': typing.Union[QSchema, str, ],
        'prefix': typing.Union[PrefixSchema, bool, ],
        'regions': typing.Union[RegionsSchema, str, ],
        'limit': typing.Union[LimitSchema, str, ],
        'offset': typing.Union[OffsetSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_q = api_client.QueryParameter(
    name="q",
    style=api_client.ParameterStyle.FORM,
    schema=QSchema,
    explode=True,
)
request_query_prefix = api_client.QueryParameter(
    name="prefix",
    style=api_client.ParameterStyle.FORM,
    schema=PrefixSchema,
    explode=True,
)
request_query_regions = api_client.QueryParameter(
    name="regions",
    style=api_client.ParameterStyle.FORM,
    schema=RegionsSchema,
    explode=True,
)
request_query_limit = api_client.QueryParameter(
    name="limit",
    style=api_client.ParameterStyle.FORM,
    schema=LimitSchema,
    explode=True,
)
request_query_offset = api_client.QueryParameter(
    name="offset",
    style=api_client.ParameterStyle.FORM,
    schema=OffsetSchema,
    explode=True,
)
# Path params


class SourceSearchLanguageSchema(
    schemas.EnumBase,
    schemas.StrSchema
):


    class MetaOapg:
        enum_value_to_name = {
            "en": "EN",
            "es": "ES",
            "nso": "NSO",
            "zu": "ZU",
            "ms": "MS",
            "id": "ID",
            "tn": "TN",
            "ur": "UR",
            "de": "DE",
            "pt": "PT",
        }
    
    @schemas.classproperty
    def EN(cls):
        return cls("en")
    
    @schemas.classproperty
    def ES(cls):
        return cls("es")
    
    @schemas.classproperty
    def NSO(cls):
        return cls("nso")
    
    @schemas.classproperty
    def ZU(cls):
        return cls("zu")
    
    @schemas.classproperty
    def MS(cls):
        return cls("ms")
    
    @schemas.classproperty
    def ID(cls):
        return cls("id")
    
    @schemas.classproperty
    def TN(cls):
        return cls("tn")
    
    @schemas.classproperty
    def UR(cls):
        return cls("ur")
    
    @schemas.classproperty
    def DE(cls):
        return cls("de")
    
    @schemas.classproperty
    def PT(cls):
        return cls("pt")


class TargetSearchLanguageSchema(
    schemas.EnumBase,
    schemas.StrSchema
):


    class MetaOapg:
        enum_value_to_name = {
            "es": "ES",
            "nso": "NSO",
            "zu": "ZU",
            "ms": "MS",
            "id": "ID",
            "tn": "TN",
            "ro": "RO",
            "de": "DE",
            "pt": "PT",
        }
    
    @schemas.classproperty
    def ES(cls):
        return cls("es")
    
    @schemas.classproperty
    def NSO(cls):
        return cls("nso")
    
    @schemas.classproperty
    def ZU(cls):
        return cls("zu")
    
    @schemas.classproperty
    def MS(cls):
        return cls("ms")
    
    @schemas.classproperty
    def ID(cls):
        return cls("id")
    
    @schemas.classproperty
    def TN(cls):
        return cls("tn")
    
    @schemas.classproperty
    def RO(cls):
        return cls("ro")
    
    @schemas.classproperty
    def DE(cls):
        return cls("de")
    
    @schemas.classproperty
    def PT(cls):
        return cls("pt")
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'source_search_language': typing.Union[SourceSearchLanguageSchema, str, ],
        'target_search_language': typing.Union[TargetSearchLanguageSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_source_search_language = api_client.PathParameter(
    name="source_search_language",
    style=api_client.ParameterStyle.SIMPLE,
    schema=SourceSearchLanguageSchema,
    required=True,
)
request_path_target_search_language = api_client.PathParameter(
    name="target_search_language",
    style=api_client.ParameterStyle.SIMPLE,
    schema=TargetSearchLanguageSchema,
    required=True,
)
_auth = [
    'appId',
    'appKey',
]
SchemaFor200ResponseBodyApplicationJson = WordlistSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: Wordlist


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: Wordlist


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
)


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
)
_status_code_to_response = {
    '200': _response_for_200,
    '404': _response_for_404,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _possible_translations_mapped_args(
        self,
        source_search_language: str,
        target_search_language: str,
        q: typing.Optional[str] = None,
        prefix: typing.Optional[bool] = None,
        regions: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if q is not None:
            _query_params["q"] = q
        if prefix is not None:
            _query_params["prefix"] = prefix
        if regions is not None:
            _query_params["regions"] = regions
        if limit is not None:
            _query_params["limit"] = limit
        if offset is not None:
            _query_params["offset"] = offset
        if source_search_language is not None:
            _path_params["source_search_language"] = source_search_language
        if target_search_language is not None:
            _path_params["target_search_language"] = target_search_language
        args.query = _query_params
        args.path = _path_params
        return args

    async def _apossible_translations_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Retrieve possible translation matches to input
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_source_search_language,
            request_path_target_search_language,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_q,
            request_query_prefix,
            request_query_regions,
            request_query_limit,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/search/{source_search_language}/translations={target_search_language}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _possible_translations_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Retrieve possible translation matches to input
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_source_search_language,
            request_path_target_search_language,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_q,
            request_query_prefix,
            request_query_regions,
            request_query_limit,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/search/{source_search_language}/translations={target_search_language}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class PossibleTranslationsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def apossible_translations(
        self,
        source_search_language: str,
        target_search_language: str,
        q: typing.Optional[str] = None,
        prefix: typing.Optional[bool] = None,
        regions: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._possible_translations_mapped_args(
            source_search_language=source_search_language,
            target_search_language=target_search_language,
            q=q,
            prefix=prefix,
            regions=regions,
            limit=limit,
            offset=offset,
        )
        return await self._apossible_translations_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def possible_translations(
        self,
        source_search_language: str,
        target_search_language: str,
        q: typing.Optional[str] = None,
        prefix: typing.Optional[bool] = None,
        regions: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._possible_translations_mapped_args(
            source_search_language=source_search_language,
            target_search_language=target_search_language,
            q=q,
            prefix=prefix,
            regions=regions,
            limit=limit,
            offset=offset,
        )
        return self._possible_translations_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class PossibleTranslations(BaseApi):

    async def apossible_translations(
        self,
        source_search_language: str,
        target_search_language: str,
        q: typing.Optional[str] = None,
        prefix: typing.Optional[bool] = None,
        regions: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> WordlistPydantic:
        raw_response = await self.raw.apossible_translations(
            source_search_language=source_search_language,
            target_search_language=target_search_language,
            q=q,
            prefix=prefix,
            regions=regions,
            limit=limit,
            offset=offset,
            **kwargs,
        )
        if validate:
            return WordlistPydantic(**raw_response.body)
        return api_client.construct_model_instance(WordlistPydantic, raw_response.body)
    
    
    def possible_translations(
        self,
        source_search_language: str,
        target_search_language: str,
        q: typing.Optional[str] = None,
        prefix: typing.Optional[bool] = None,
        regions: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        validate: bool = False,
    ) -> WordlistPydantic:
        raw_response = self.raw.possible_translations(
            source_search_language=source_search_language,
            target_search_language=target_search_language,
            q=q,
            prefix=prefix,
            regions=regions,
            limit=limit,
            offset=offset,
        )
        if validate:
            return WordlistPydantic(**raw_response.body)
        return api_client.construct_model_instance(WordlistPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        source_search_language: str,
        target_search_language: str,
        q: typing.Optional[str] = None,
        prefix: typing.Optional[bool] = None,
        regions: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._possible_translations_mapped_args(
            source_search_language=source_search_language,
            target_search_language=target_search_language,
            q=q,
            prefix=prefix,
            regions=regions,
            limit=limit,
            offset=offset,
        )
        return await self._apossible_translations_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        source_search_language: str,
        target_search_language: str,
        q: typing.Optional[str] = None,
        prefix: typing.Optional[bool] = None,
        regions: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._possible_translations_mapped_args(
            source_search_language=source_search_language,
            target_search_language=target_search_language,
            q=q,
            prefix=prefix,
            regions=regions,
            limit=limit,
            offset=offset,
        )
        return self._possible_translations_oapg(
            query_params=args.query,
            path_params=args.path,
        )

