# coding: utf-8

# flake8: noqa

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.11.0"

# import ApiClient
from oxford_dictionaries_python_sdk.api_client import ApiClient

# import Configuration
from oxford_dictionaries_python_sdk.configuration import Configuration

# import exceptions
from oxford_dictionaries_python_sdk.exceptions import OpenApiException
from oxford_dictionaries_python_sdk.exceptions import ApiAttributeError
from oxford_dictionaries_python_sdk.exceptions import ApiTypeError
from oxford_dictionaries_python_sdk.exceptions import ApiValueError
from oxford_dictionaries_python_sdk.exceptions import ApiKeyError
from oxford_dictionaries_python_sdk.exceptions import ApiException

from oxford_dictionaries_python_sdk.client import OxfordDictionaries
