# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from oxford_dictionaries_python_sdk.pydantic.arrayofstrings import Arrayofstrings
from oxford_dictionaries_python_sdk.pydantic.categorized_text_list import CategorizedTextList
from oxford_dictionaries_python_sdk.pydantic.grammatical_features_list import GrammaticalFeaturesList
from oxford_dictionaries_python_sdk.pydantic.pronunciations_list import PronunciationsList
from oxford_dictionaries_python_sdk.pydantic.sense import Sense
from oxford_dictionaries_python_sdk.pydantic.variant_forms_list import VariantFormsList

class Entry(BaseModel):
    etymologies: typing.Optional[Arrayofstrings] = Field(None, alias='etymologies')

    grammatical_features: typing.Optional[GrammaticalFeaturesList] = Field(None, alias='grammaticalFeatures')

    # Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
    homograph_number: typing.Optional[str] = Field(None, alias='homographNumber')

    notes: typing.Optional[CategorizedTextList] = Field(None, alias='notes')

    pronunciations: typing.Optional[PronunciationsList] = Field(None, alias='pronunciations')

    # Complete list of senses
    senses: typing.Optional[typing.List[Sense]] = Field(None, alias='senses')

    variant_forms: typing.Optional[VariantFormsList] = Field(None, alias='variantForms')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
