# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from oxford_dictionaries_python_sdk.pydantic.arrayofstrings import Arrayofstrings

class PronunciationsListItem(BaseModel):
    # The URL of the sound file
    audio_file: typing.Optional[str] = Field(None, alias='audioFile')

    dialects: typing.Optional[Arrayofstrings] = Field(None, alias='dialects')

    # The alphabetic system used to display the phonetic spelling
    phonetic_notation: typing.Optional[str] = Field(None, alias='phoneticNotation')

    # Phonetic spelling is the representation of vocal sounds which express pronunciations of words. It is a system of spelling in which each letter represents invariably the same spoken sound
    phonetic_spelling: typing.Optional[str] = Field(None, alias='phoneticSpelling')

    regions: typing.Optional[Arrayofstrings] = Field(None, alias='regions')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
