# coding: utf-8

"""
    Oxford Dictionaries

    Oxford Dictionaries, part of the Oxford Language Division, is a leading authority on the English language. It offers a wide range of language resources, including dictionaries, thesauruses, grammar guides, and language learning tools. Oxford Dictionaries provides accurate and up-to-date definitions, word origins, and usage examples to support language comprehension and communication.

    The version of the OpenAPI document: 1.11.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from oxford_dictionaries_python_sdk.pydantic.sentences_lexical_entry import SentencesLexicalEntry

class SentencesEntry(BaseModel):
    # The identifier of a word
    id: str = Field(alias='id')

    # IANA language code
    language: str = Field(alias='language')

    # A grouping of various senses in a specific language, and a lexical category that relates to a word
    lexical_entries: typing.List[SentencesLexicalEntry] = Field(alias='lexicalEntries')

    # A given written or spoken realisation of a an entry, lowercased.
    word: str = Field(alias='word')

    # The json object type. Could be 'headword', 'inflection' or 'phrase'
    type: typing.Optional[str] = Field(None, alias='type')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
